'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { API } from '@/lib/api'
import { CheckCircle, XCircle, Clock, FileText } from 'lucide-react'

function fmtDate(d) {
  if (!d) return ''
  const s = typeof d === 'string' ? d.split('T')[0] : d
  return new Date(s + 'T12:00:00').toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

export default function LetterVerificationPage() {
  const { id } = useParams()
  const [state, setState] = useState({ loading: true, data: null, error: null })

  useEffect(() => {
    if (!id) return
    fetch(`${API}/api/letters/verify/${encodeURIComponent(id)}`)
      .then(async r => {
        const d = await r.json().catch(() => ({}))
        if (!r.ok && r.status !== 404) throw new Error(d.error || `HTTP ${r.status}`)
        return d
      })
      .then(data => setState({ loading: false, data, error: null }))
      .catch(err => setState({ loading: false, data: null, error: err.message }))
  }, [id])

  const loading = state.loading
  const data = state.data
  const letter = data?.letter
  const valid = data?.valid === true
  const pending = data?.status === 'pending'

  const Icon = loading ? Clock : valid ? CheckCircle : pending ? Clock : XCircle
  const color = loading ? '#B8860B' : valid ? '#059669' : pending ? '#D97706' : '#DC2626'
  const bg = loading ? '#FFFBEB' : valid ? '#ECFDF5' : pending ? '#FFFBEB' : '#FEF2F2'
  const border = loading ? '#FDE68A' : valid ? '#A7F3D0' : pending ? '#FDE68A' : '#FCA5A5'
  const title = loading ? 'Checking Document' : valid ? 'Document Valid' : pending ? 'Document Pending Approval' : 'Document Not Valid'
  const message = loading
    ? 'Please wait while we verify this document.'
    : data?.message || state.error || 'This document could not be verified.'

  return (
    <main style={{ minHeight:'100vh', background:'#F8F7F4', display:'flex', alignItems:'center', justifyContent:'center', padding:20, fontFamily:'Poppins, Arial, sans-serif' }}>
      <section style={{ width:'100%', maxWidth:520, background:'#fff', border:'1px solid #E7E2D8', borderRadius:16, boxShadow:'0 16px 50px rgba(0,0,0,0.08)', overflow:'hidden' }}>
        <div style={{ padding:'26px 28px', borderBottom:'1px solid #E7E2D8', display:'flex', alignItems:'center', gap:14 }}>
          <img src="/logo.webp" alt="Golden Crescent" style={{ width:52, height:52, objectFit:'contain', borderRadius:10 }}/>
          <div>
            <div style={{ fontSize:16, fontWeight:800, color:'#1A1612' }}>Golden Crescent</div>
            <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.14em', textTransform:'uppercase', color:'#B8860B' }}>Document Verification</div>
          </div>
        </div>

        <div style={{ padding:28 }}>
          <div style={{ background:bg, border:`1px solid ${border}`, borderRadius:14, padding:'20px 18px', display:'flex', gap:14, alignItems:'flex-start' }}>
            <Icon size={34} color={color} style={{ flexShrink:0 }}/>
            <div>
              <h1 style={{ margin:'0 0 5px', color, fontSize:22, lineHeight:1.2 }}>{title}</h1>
              <p style={{ margin:0, color:'#4B5563', fontSize:13.5, lineHeight:1.6 }}>{message}</p>
            </div>
          </div>

          {letter && (
            <div style={{ marginTop:22, border:'1px solid #E7E2D8', borderRadius:12, overflow:'hidden' }}>
              {[
                ['Reference', letter.ref_no],
                ['Date', fmtDate(letter.date)],
                ['Recipient', letter.to_name || 'To Whom It May Concern'],
                ['Subject', letter.subject || 'N/A'],
                ['Generated By', letter.created_by_name || 'N/A'],
                ['Status', letter.status],
              ].map(([label, value]) => (
                <div key={label} style={{ display:'grid', gridTemplateColumns:'130px 1fr', borderBottom:label==='Status'?'none':'1px solid #EEEAE2' }}>
                  <div style={{ padding:'11px 14px', background:'#FAFAF8', color:'#8A7A62', fontSize:11, fontWeight:800, textTransform:'uppercase', letterSpacing:'0.04em' }}>{label}</div>
                  <div style={{ padding:'11px 14px', color:'#1A1612', fontSize:13, fontWeight:label==='Status'?800:600, textTransform:label==='Status'?'capitalize':'none' }}>{value}</div>
                </div>
              ))}
            </div>
          )}

          {!letter && !loading && (
            <div style={{ marginTop:22, display:'flex', alignItems:'center', gap:10, color:'#6B7280', fontSize:13, lineHeight:1.6 }}>
              <FileText size={18}/>
              <span>Please confirm the QR code was scanned from an official Golden Crescent document.</span>
            </div>
          )}
        </div>
      </section>
    </main>
  )
}
