import { CheckCircle, XCircle, Clock, FileText } from 'lucide-react'

const _raw = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'
const BASE = _raw.startsWith('http') ? _raw : `https://${_raw}`

function fmtDate(d) {
  if (!d) return ''
  const s = typeof d === 'string' ? d.split('T')[0] : d
  return new Date(s + 'T12:00:00').toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })
}

export default async function LetterVerificationPage({ params }) {
  const { id } = params

  let data = null
  let fetchError = null

  try {
    const res = await fetch(`${BASE}/api/letters/verify/${id}`, { cache: 'no-store' })
    data = await res.json().catch(() => null)
    if (!data) fetchError = `Unexpected server response (status ${res.status})`
  } catch (err) {
    fetchError = err.message
  }

  const letter  = data?.letter
  const valid   = data?.valid === true
  const pending = data?.status === 'pending'

  const Icon    = valid ? CheckCircle : pending ? Clock : XCircle
  const color   = valid ? '#059669'   : pending ? '#D97706' : '#DC2626'
  const bg      = valid ? '#ECFDF5'   : pending ? '#FFFBEB' : '#FEF2F2'
  const border  = valid ? '#A7F3D0'   : pending ? '#FDE68A' : '#FCA5A5'
  const title   = valid ? 'Document Valid' : pending ? 'Awaiting Approval' : 'Document Not Valid'
  const message = data?.message || fetchError || 'This document could not be verified.'

  return (
    <main style={{ minHeight:'100vh', background:'#F8F7F4', display:'flex', alignItems:'center', justifyContent:'center', padding:20, fontFamily:'Poppins, Arial, sans-serif' }}>
      <section style={{ width:'100%', maxWidth:520, background:'#fff', border:'1px solid #E7E2D8', borderRadius:16, boxShadow:'0 16px 50px rgba(0,0,0,0.08)', overflow:'hidden' }}>

        <div style={{ padding:'26px 28px', borderBottom:'1px solid #E7E2D8', display:'flex', alignItems:'center', gap:14 }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/logo.webp" alt="Golden Crescent" style={{ width:52, height:52, objectFit:'contain', borderRadius:10 }}/>
          <div>
            <div style={{ fontSize:16, fontWeight:800, color:'#1A1612' }}>Golden Crescent</div>
            <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.14em', textTransform:'uppercase', color:'#B8860B' }}>Document Verification</div>
          </div>
        </div>

        <div style={{ padding:28 }}>
          <div style={{ background:bg, border:`1px solid ${border}`, borderRadius:14, padding:'20px 18px', display:'flex', gap:14, alignItems:'flex-start' }}>
            <Icon size={34} color={color} style={{ flexShrink:0 }}/>
            <div>
              <h1 style={{ margin:'0 0 5px', color, fontSize:22, lineHeight:1.2 }}>{title}</h1>
              <p style={{ margin:0, color:'#4B5563', fontSize:13.5, lineHeight:1.6 }}>{message}</p>
            </div>
          </div>

          {letter && (
            <div style={{ marginTop:22, border:'1px solid #E7E2D8', borderRadius:12, overflow:'hidden' }}>
              {[
                ['Reference',    letter.ref_no],
                ['Date',         fmtDate(letter.date)],
                ['Recipient',    letter.to_name || 'To Whom It May Concern'],
                ['Subject',      letter.subject || 'N/A'],
                ['Generated By', letter.created_by_name || 'N/A'],
                ['Status',       letter.status],
              ].map(([label, value], i, arr) => (
                <div key={label} style={{ display:'grid', gridTemplateColumns:'130px 1fr', borderBottom: i < arr.length - 1 ? '1px solid #EEEAE2' : 'none' }}>
                  <div style={{ padding:'11px 14px', background:'#FAFAF8', color:'#8A7A62', fontSize:11, fontWeight:800, textTransform:'uppercase', letterSpacing:'0.04em' }}>{label}</div>
                  <div style={{ padding:'11px 14px', color:'#1A1612', fontSize:13, fontWeight: label === 'Status' ? 800 : 600, textTransform: label === 'Status' ? 'capitalize' : 'none' }}>{value}</div>
                </div>
              ))}
            </div>
          )}

          {!letter && (
            <div style={{ marginTop:22, display:'flex', alignItems:'center', gap:10, color:'#6B7280', fontSize:13, lineHeight:1.6 }}>
              <FileText size={18}/>
              <span>Please confirm the QR code was scanned from an official Golden Crescent document.</span>
            </div>
          )}
        </div>
      </section>
    </main>
  )
}
